### ISSUE TITLE
flask-debugtoolbar is incompatible with newest version of werkzeug.

### ISSUE THREAD

**Issue by JB0925** [pallets-eco/flask-debugtoolbar#209] opened 2023-10-03 20:14 UTC
Hello. When trying to use `flask-debugtoolbar` with any version of the more recent versions of `flask`, users are running into the following or some variation thereof:
```
 File "/Users/username/toolbar-test/venv/lib/python3.10/site-packages/flask_debugtoolbar/__init__.py", line 8, in <module>
    from werkzeug.urls import url_quote_plus
ImportError: cannot import name 'url_quote_plus' from 'werkzeug.urls' (/Users/username/toolbar-test/venv/lib/python3.10/site-packages/werkzeug/urls.py)

```

I've determined that this is because of a change to `werkzeug`. It was also bumped to version 3.0.0 within the last few days and, no matter what flask version you use, it now installs with `werkzeug==3.0.0` by default.

## A Workaround
For the time being, users can run `pip install "flask<=2.3.3" && pip install "werkzeug<=2.3.7"`.

I just wanted to make mention of the issue here for visibility.

Edit: I was going to create a PR to address this, but I see that one has already been created.

**Comment by nickjj** [comment] 2023-10-06 12:43
Thanks. There's https://github.com/pallets-eco/flask-debugtoolbar/pull/207 to address this.

**Comment by nickjj** [comment] 2023-10-06 22:20
Since #207 got merged we're good to go here. The issue is solved on the master branch.

**Closed by nickjj** 2023-10-06 22:20 UTC
